# Give the project a nice name
spring.application.name: backend

# Set the port
server.port: ${SERVER_PORT:8081}

# Enable all the actuator endpoints for HTTP (keep them under the base path) and JMX
management.endpoints:
  web:
    base-path: /
    exposure.include: "*"
  jmx.exposure.include: "*"

spring.jpa.hibernate.ddl-auto: create
spring.datasource.url: jdbc:mysql://${DATABASE_SERVER:localhost}:${DATABASE_PORT:3306}/${DATABASE_NAME:person}
spring.datasource.username: ${DATABASE_USERNAME:root}
spring.datasource.password: ${DATABASE_PASSWORD:}
