- hosts: all
  remote_user: ubuntu
  become: true
  gather_facts: yes


  vars_files:
    - variables.yml


  vars:
      kibana_basic_auth: "{{ attendee_user }}:{{ attendee_password  }}"


  pre_tasks:
    - name: Install Python2 to make Ansible work
      raw: sudo apt-get update && sudo apt-get -y install python-minimal


  post_tasks:
    - include_tasks: include_event.yml
      vars:
        application: configure_all


  tasks:


    # System
    - name: Update and upgrade apt packages
      apt: upgrade=dist

    - name: Install NTP to avoid time drift and PIP to manage Python dependencies plus its build tools
      apt: name={{ item }}
      with_items:
        - ntp
        - ntpdate
        - python3-pip
        - build-essential
        - libssl-dev
        - libffi-dev

    - name: Install the JRE
      apt: name=openjdk-8-jre-headless install_recommends=no

    - name: Install the pyOpenSSL library, so Ansible can use it to check TLS certificates
      pip: name=pyopenssl


    # osquery
    - name: Add osquery's repository key
      apt_key:
        keyserver: keyserver.ubuntu.com
        id: 1484120AC4E9F8A1A577AEEE97A80C63C9D8B80B
        state: present

    - name: Add osquery's server repository
      apt_repository:
        repo: "deb [arch=amd64] https://osquery-packages.s3.amazonaws.com/{{ ansible_distribution_release }} {{ ansible_distribution_release }} main"
        state: present

    - name: Install osquery
      apt: name=osquery update_cache=true

    - name: Stop osquery since it sometimes need a few seconds between stop and start to work properly
      service: name=osqueryd state=stopped

    - name: Allow osquery to access the rsyslog.conf
      blockinfile:
        path: /etc/rsyslog.conf
        block: |
          template(
            name="OsqueryCsvFormat"
            type="string"
            string="%timestamp:::date-rfc3339,csv%,%hostname:::csv%,%syslogseverity:::csv%,%syslogfacility-text:::csv%,%syslogtag:::csv%,%msg:::csv%\n"
          )
          *.* action(type="ompipe" Pipe="/var/osquery/syslog_pipe" template="OsqueryCsvFormat")

    - name: Restart rsyslog
      service: name=rsyslog state=restarted

    - name: Provide the base configuration for osquery
      template: src=templates/osquery.conf dest=/etc/osquery/osquery.conf

    - name: Get the it-compliance configuration
      get_url:
        url: https://raw.githubusercontent.com/facebook/osquery/master/packs/it-compliance.conf
        dest: /etc/osquery/it-compliance.conf
        mode: 0644

    - name: Get the ossec-rootkit configuration
      get_url:
        url: https://raw.githubusercontent.com/facebook/osquery/master/packs/ossec-rootkit.conf
        dest: /etc/osquery/ossec-rootkit.conf
        mode: 0644

    - name: Restart osquery and make sure it autostarts
      service: name=osqueryd state=restarted enabled=yes


    # Global Elasticsearch configuration
    - name: Register a global index template
      uri:
        url: "{{elasticsearch_host}}_template/template_global"
        body_format: json
        method: PUT
        user: "{{ elasticsearch_user }}"
        password: "{{ elasticsearch_password }}"
        body:
          template: "*"
          settings:
            number_of_shards: 1
            number_of_replicas: 0
            refresh_interval: 2s
        status_code:
          - 201
          - 200
      run_once: true


    # Auditbeat
    - name: Install Auditbeat
      apt: deb={{ elastic_download }}/downloads/beats/auditbeat/auditbeat-{{ elastic_version }}-amd64.deb

    - name: Change the Auditbeat configuration
      template: src=templates/auditbeat.yml dest=/etc/auditbeat/auditbeat.yml

    - name: Restart Auditbeat and make sure it autostarts
      service: name=auditbeat state=restarted enabled=yes


    # Filebeat
    - name: Install Filebeat
      apt: deb={{ elastic_download }}/downloads/beats/filebeat/filebeat-{{ elastic_version }}-amd64.deb

    - name: Change the Filebeat configuration
      template: src=templates/filebeat.yml dest=/etc/filebeat/filebeat.yml

    - name: Restart Filebeat and make sure it autostarts
      service: name=filebeat state=restarted enabled=yes


    # Metricbeat
    - name: Install Metricbeat
      apt: deb={{ elastic_download }}/downloads/beats/metricbeat/metricbeat-{{ elastic_version }}-amd64.deb

    - name: Change the Metricbeat configuration
      template: src=templates/metricbeat.yml dest=/etc/metricbeat/metricbeat.yml

    - name: Restart Metricbeat and make sure it autostarts
      service: name=metricbeat state=restarted enabled=yes

    #- name: Set metricbeat-* as the default index pattern
    #  uri:
    #    url: "{{kibana_host}}api/kibana/settings/defaultIndex"
    #    body_format: json
    #    method: POST
    #    user: "{{ elasticsearch_user }}"
    #    password: "{{ elasticsearch_password }}"
    #    headers:
    #      kbn-xsrf: kibana
    #    body:
    #      value: metricbeat-*
    #    status_code:
    #      - 201
    #      - 200
    #  run_once: true


    # Packetbeat
    - name: Install Packetbeat
      apt: deb={{ elastic_download }}/downloads/beats/packetbeat/packetbeat-{{ elastic_version }}-amd64.deb

    - name: Change the Packetbeat configuration
      template: src=templates/packetbeat.yml dest=/etc/packetbeat/packetbeat.yml

    - name: Restart Packetbeat and make sure it autostarts
      service: name=packetbeat state=restarted enabled=yes


    # APM
    - name: Fetch the APM agent
      get_url:
        url: "https://search.maven.org/remotecontent?filepath=co/elastic/apm/elastic-apm-agent/{{ apm_java }}/elastic-apm-agent-{{ apm_java }}.jar"
        dest: "/opt/elastic-apm-agent-{{ apm_java }}.jar"
        mode: 0444


    # nginx
    - name: Install nginx
      apt: name=nginx

    - name: Stop nginx so that Certbot can bind to port 80
      service: name=nginx state=stopped

    - name: Add the certbot repository
      apt_repository: repo="ppa:certbot/certbot"

    - name: Install certbot and update the cache for the new PPA
      apt: name=python-certbot-nginx update_cache=yes

    - name: Add the hostname to the certificates to create
      set_fact:
        certificates:
          - "{{ inventory_hostname }}"

    - name: Add more domains to the frontend certificate
      set_fact:
        certificates:
          - "{{ inventory_hostname }}"
          - "{{ domain }}"
          - "www.{{ domain }}"
      when: inventory_hostname == "frontend." + domain

    - name: Add more domains to the monitor certificate
      set_fact:
        certificates:
          - "{{ inventory_hostname }}"
          - "kibana.{{ domain }}"
          - "dashboard.{{ domain }}"
      when: inventory_hostname == "monitor." + domain

    - name: Create the certificate
      command: >
        certbot certonly --non-interactive --standalone
        --agree-tos --email admin@{{ domain }}
        -d {{ certificates | join(',') }}
        creates=/etc/letsencrypt/live/{{ inventory_hostname }}/fullchain.pem

    - name: Add crontab to renew certificates every second month on Sunday night
      cron: minute="30" hour="3" weekday="0" month="*/2" job="service nginx stop && certbot renew >> /var/log//var/log/letsencrypt/renew.log && service nginx start"

    - name: Generate strong dhparams, but only if the file doesn't exist
      command: openssl dhparam -out /etc/ssl/certs/dhparam.pem 2048 creates=/etc/ssl/certs/dhparam.pem

    - name: Set a global TLS configuration
      template: src=templates/tls.conf dest=/etc/nginx/tls.conf

    - name: Change the nginx configuration
      template: src=templates/nginx.conf dest=/etc/nginx/sites-available/default

    - name: Restart nginx and make sure it autostarts
      service: name=nginx state=restarted enabled=yes

    - name: Check HTTP
      uri:
        url: "http://{{ inventory_hostname }}"
        follow_redirects: none
        status_code: 301
      register: response
      retries: 3
      delay: 2
      delegate_to: 127.0.0.1
      become: false

    - name: Fail if HTTP is not being redirected to HTTPS
      fail:
      when: response.status != 301

    - name: Check HTTPS
      openssl_certificate:
        path: /etc/letsencrypt/live/{{ inventory_hostname }}/fullchain.pem
        provider: assertonly
        issuer:
          O: Let's Encrypt
        has_expired: false
        subject_alt_name:
          - "DNS:{{ inventory_hostname }}"

    - name: Check HTTPS apex
      openssl_certificate:
        path: /etc/letsencrypt/live/{{ inventory_hostname }}/fullchain.pem
        provider: assertonly
        issuer:
          O: Let's Encrypt
        has_expired: false
        subject_alt_name:
          - "DNS:{{ domain }}"
      when: inventory_hostname == "frontend." + domain
